# Aggregations
#### summing the values in an Array

In [1]:
import numpy as np


In [2]:
L = np.random.random(100)
sum(L)

np.float64(54.34487044712532)

In [3]:
np.sum(L)

np.float64(54.34487044712532)

In [4]:
big_array = np.random.rand(1000000)
%timeit -n10 sum(big_array)
%timeit np.sum(big_array)

72 ms ± 3.21 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
854 μs ± 39.4 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


# Min and Max

In [5]:
min(big_array), max(big_array)

(np.float64(5.690919860912302e-07), np.float64(0.9999995266450482))

In [6]:
np.min(big_array), np.max(big_array)

(np.float64(5.690919860912302e-07), np.float64(0.9999995266450482))

In [7]:
%timeit min(big_array)
%timeit np.min(big_array)

51.4 ms ± 516 μs per loop (mean ± std. dev. of 7 runs, 10 loops each)
398 μs ± 16.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Multi dimensional aggregates

In [8]:
M = np.arange(0,6).reshape((2,3))
print(M)

[[0 1 2]
 [3 4 5]]


In [9]:
M.sum() # equivalent to np.sum(M) but not sum(M)

np.int64(15)

In [10]:
M.sum(axis=0)

array([3, 5, 7])

In [27]:
M.sum(axis=0,keepdims=True) # to keep the same dimentions

array([[3, 5, 7]])

In [11]:
M.sum(axis=1)

array([ 3, 12])

![alt text](4214_t2-3.PNG)

In [12]:
l = np.random.randint(10,100,size=10)
l

array([76, 40, 69, 86, 72, 49, 16, 45, 40, 34], dtype=int32)

In [13]:
l.min()

np.int32(16)

In [14]:
l.argmin()

np.int64(6)

In [15]:
l2 = np.random.randint(10,100,size=11)
l2

array([62, 47, 11, 21, 16, 55, 92, 13, 62, 31, 50], dtype=int32)

In [17]:
np.median(l2)

np.float64(47.0)

In [18]:
np.sort(l2)

array([11, 13, 16, 21, 31, 47, 50, 55, 62, 62, 92], dtype=int32)

In [21]:
np.percentile(l2,75)

np.float64(58.5)

In [22]:
np.percentile(l2,[25,75])

array([18.5, 58.5])

In [24]:
l = np.array([np.nan,5,np.nan,6,10,19])
l

array([nan,  5., nan,  6., 10., 19.])

In [25]:
l.sum()

np.float64(nan)

In [26]:
np.nansum(l)

np.float64(40.0)