# Broadcasting
#### Broadcasting is simply a set of rules for applying binary ufuncs (addition,subtraction,multiplication,etc) on arrays of different sizes

In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2])
b = np.array([5,5,5])
print(a)
print(b)
print(a+b)

[0 1 2]
[5 5 5]
[5 6 7]


![alt text](02.05-broadcasting.png)

In [3]:
a+5 # [0,1,2] + 5 -> [5,5,5]

array([5, 6, 7])

In [5]:
M = np.ones((3,3))
M,a

(array([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]),
 array([0, 1, 2]))

In [6]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [7]:
a = np.arange(3)
b = np.arange(3)[:,np.newaxis] # (3,) -> (3,1)

print(a)
print(b)

[0 1 2]
[[0]
 [1]
 [2]]


In [8]:
a+b  
#      0    1    2
#  0   0    1    2
#  1   1    2    3
#  2   2    3    4

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Rules of Broadcasting
Broadcasting in NumPy follows a strict set of rules to determine the interaction between the two arrays:

- Rule 1: If the two arrays differ in their number of dimensions, the shape of the one with fewer dimensions is padded with ones on its leading (left) side.
- Rule 2: If the shape of the two arrays does not match in any dimension, the array with shape equal to 1 in that dimension is stretched to match the other shape.
- Rule 3: If in any dimension the sizes disagree and neither is equal to 1, an error is raised.

In [9]:
M = np.ones((2,3))
a = np.arange(3)

In [10]:
print("M.shape", M.shape)
print("a.shape",a.shape) # will be rule1 (1,3) rule2 (2,3) to match the other array

M.shape (2, 3)
a.shape (3,)


In [11]:
M + a

array([[1., 2., 3.],
       [1., 2., 3.]])

In [13]:
a = np.arange(3).reshape((3, 1)) # (3,1)
b = np.arange(3) # (3,)
"""
Rule 1 says we must pad the shape of b with ones:

a.shape -> (3, 1)
b.shape -> (1, 3)
"""
"""
And rule 2 tells us that we upgrade each of these ones to match the corresponding size of the other array:

a.shape -> (3, 3)
b.shape -> (3, 3)
"""
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])