# Multidimensional subarrays

In [1]:
import numpy as np

In [2]:
x2 = np.array([[12,5,2,4],[7,6,8,8],[1,6,7,7]])
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [3]:
x2[0:2,2:3] # row 1 and 2 with the column 2

array([[2],
       [8]])

In [4]:
x2[:2,:3] # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [5]:
x2[1:,3:] # row 1 and column 3

array([[8],
       [7]])

In [6]:
x2[:3,::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [7]:
x2[1,1:3]

array([6, 8])

In [8]:
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [9]:
x2[:2,::-1]

array([[ 4,  2,  5, 12],
       [ 8,  8,  6,  7]])