# Creating numpy arrays
### from python list

In [1]:
import numpy as np
# integer array:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [2]:
np.array([3.14,4,2,3]) # all elements are considered of the same type

array([3.14, 4.  , 2.  , 3.  ])

In [3]:
np.array([1, 2, 3, 4],dtype="float32") # to explictily set the data type

array([1., 2., 3., 4.], dtype=float32)

# From Scratch

In [4]:
# Create a length-10 integer array filled with zeros
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [5]:
# Create a 3x5 floating array filled with 1s
np.ones((3,5),dtype=float) # 3 rows and 5 columns

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
# Create a 3x5 array filled with 2.75
np.full((3,5),2.75)

array([[2.75, 2.75, 2.75, 2.75, 2.75],
       [2.75, 2.75, 2.75, 2.75, 2.75],
       [2.75, 2.75, 2.75, 2.75, 2.75]])

In [7]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, steping by 2

np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3,3))

array([[0.74959154, 0.06491752, 0.46400438],
       [0.34521285, 0.85108123, 0.79565776],
       [0.14906056, 0.04391071, 0.49329452]])

In [9]:
# Create a 3x3 array normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0,1,(3,3))

array([[-0.01120005, -1.24434835,  0.48233107],
       [ 0.22649344,  0.70557957,  1.64068173],
       [ 0.33231864,  1.27781716,  0.40255544]])

In [10]:
# Create a 3x3 random integers in the interval [0,10]
np.random.randint(0,10,(3,3))

array([[7, 9, 9],
       [8, 4, 8],
       [4, 5, 1]])

In [12]:
# Create a 3x3 identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exists at that memory location
np.empty(3)

array([ 9.14689138e-312,  0.00000000e+000, -6.47591605e-319])