# Numpy Array Attributes

In [23]:
import numpy as np
x = np.zeros((3,4,5))
x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [3]:
print("x ndim:",x.ndim)
print("x shape:",x.shape)
print("x size:",x.size)
print("dtype:",x.dtype)

x ndim: 3
x shape: (3, 4, 5)
x size: 60
dtype: float64


# Array Indexing

In [4]:
x1 = np.array([5,0,3,3,7,9])
x1


array([5, 0, 3, 3, 7, 9])

In [5]:
x1[0] # first element in the array

5

In [6]:
x1[3] # the forth element as the array is zero based

3

In [7]:
x2=np.array([[3,5,2,4],[7,6,8,8],[1,6,7,7]])
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [8]:
x2[0,0] # row 1 column 1 as we mentioned numpy array is zero based 

3

In [9]:
x2[2,0] # row 3 column 1 

1

In [10]:
x2[0,0] = 5 # we assign new value in certein index
x2

array([[5, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

# Array Slicing: Accessing Subarrays
## One-dimentional subarrays

In [12]:
x = np.arange(10) # making array from 0 to 9 as its a 10 element
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[1:5] # from index 1 to index 5

array([1, 2, 3, 4])

In [14]:
x[:3] # first 3 elemnts

array([0, 1, 2])

In [15]:
x[5:] # from the fifth to the last one

array([5, 6, 7, 8, 9])

In [16]:
x[4:7] # middle subarray

array([4, 5, 6])

In [17]:
x[::2] # form the start to the end with step two

array([0, 2, 4, 6, 8])

In [18]:
x[::-1] # to reverse the numpy array

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [19]:
x[5::-2] # reverse from the fifth to the first element with step -2

array([5, 3, 1])

In [22]:
n = np.random.randint(2,20,10) # creates a numpy array with random integers from 2 to 20 and i want 10 elements
n

array([15,  2,  8, 13, 15,  4,  2,  6,  9,  5])