# Reshaping of Arrays

In [2]:
import numpy as np

In [2]:
grid = np.arange(1,10)
grid

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
grid = grid.reshape((3,3)) # rehsap the original array in to 3x3 matrix 
grid


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
# in one line 
grid = np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
grid = np.arange(0,12).reshape((6,2))
grid

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [8]:
x = np.array([1,2,3])
# * row vector via reshape
x.reshape((1,3))

array([[1, 2, 3]])

# Array Concatenation

In [3]:
# used to concate two arrays
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [4]:
# if we want to concatenate 3 arrays
z = np.array([99,99,99])
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [7]:
# for 2D arrays
x = np.full((2,3),1)
y = np.full((2,3),9)
print(x)
print()
print(y)

[[1 1 1]
 [1 1 1]]

[[9 9 9]
 [9 9 9]]


In [8]:
# concatenate along the first axis
np.concatenate([x,y],axis=0)
# here the dimension of x is (2,3) and y is (2,3) so when we concatenate
# along the axis zero so we made it along the rows so (2,3) + (2,3) = (4,3)

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [9]:
np.concatenate([x,y],axis=0).shape

(4, 3)

In [10]:
# concatenate along the second axis
np.concatenate([x,y],axis=1)
# (2,3) + (2,3) = (2,6)

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

In [11]:
np.concatenate([x,y],axis=1).shape

(2, 6)

In [13]:
# alternative ways 
x = np.array([1,2,3])
y = np.array([[9,8,7],[6,5,4]])


In [20]:
x = x.reshape((1,-1))
x

array([[1, 2, 3]])

In [21]:
y

array([[9, 8, 7],
       [6, 5, 4]])

In [24]:
np.concatenate([x,y],axis=0) # because the number of columns is equal we can we can concatenate in axis 0

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [25]:
# another way vertical stack the arrays
np.vstack([x,y])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [26]:
# Here we didn't make reshape for x the vstack made it for us
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [28]:
print(grid)


[[9 8 7]
 [6 5 4]]


In [29]:
# horizontally stack the array
y = np.array([[99],[99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

# Spliting of arrays

In [30]:
x = [1,2,3,99,99,3,2,1]
x1,x2,x3 = np.split(x,[3,5]) # N split points lead to N + 1 subarrays
# [3,5] are the indexing that we want to make the spliting on
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


In [31]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
upper, lower = np.vsplit(grid,[2]) # spliting vertically in index 2
print(upper)
print()
print(lower)

[[0 1 2 3]
 [4 5 6 7]]

[[ 8  9 10 11]
 [12 13 14 15]]


In [36]:
upper, lower, last = np.vsplit(grid,[1,3]) # spliting vertically in index 1 and 3
print(upper)
print()
print(lower)
print()
print(last)


[[0 1 2 3]]

[[ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]]


In [39]:
left,right  = np.hsplit(grid,[2]) # spliting index 2
print(left)
print()
print(right)



[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [44]:
left, middle, right = np.hsplit(grid,[2,3]) # spliting horizontaly in index 2 and 3
print(left)
print()
print(middle)
print()
print(middle)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

[[ 2]
 [ 6]
 [10]
 [14]]

[[ 2]
 [ 6]
 [10]
 [14]]
