# U funcs
 - numpy provides an easy and flexible interface to optimized computation with array of data.
 - Vectorization is the key for numpy arrays to be fast
 
 - Vectorization is implemented through universal functions

In [1]:
import numpy as np


In [7]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

values = np.random.randint(1,10,size=5)
compute_reciprocals(values)    

array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

In [10]:
big_array = np.random.randint(1,100,size=1000000)
%timeit compute_reciprocals(big_array)

1.49 s ± 22.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [11]:
%timeit 1./big_array

2.52 ms ± 77.3 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Exploring Numpys UFuncs

In [2]:
x = np.arange(4)
print("x =",x)
print("x + 5=",x + 5) # np.add(x,2)
print("x - 5=",x - 5)
print("x * 2",x*2) # np.multiply(x,2)

x = [0 1 2 3]
x + 5= [5 6 7 8]
x - 5= [-5 -4 -3 -2]
x * 2 [0 2 4 6]


In [3]:
print("x / 2 =",x / 2)
print("x // 2 =",x // 2) # floor division
print("-x =",-x)
print("x ** 2 =",x**2)
print("x % 2 =",x % 2)

x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]
-x = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2 = [0 1 0 1]


![alt text](4214_t2-2.png)

### Absolute value

In [4]:
x = np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

In [6]:
print(np.absolute(x))
print(np.abs(x))

[2 1 0 1 2]
[2 1 0 1 2]


In [7]:
big_array = np.random.randint(-10,10,size=1000000)
%timeit np.abs(big_array)
%timeit abs(big_array)

1.5 ms ± 58.2 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
1.5 ms ± 57 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


### Trignometric functions

In [12]:
theta = np.linspace(0,np.pi,3)
print(theta)
print(np.degrees(theta))

[0.         1.57079633 3.14159265]
[  0.  90. 180.]


In [10]:
print("theta =",theta)
print("sin(theta) = ",np.sin(theta))
print("sin(theta) = ",np.cos(theta))
print("sin(theta) = ",np.tan(theta))

theta = [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
sin(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
sin(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [11]:
x = [-1,0,1]
print("x = ",x)
print("x = ",np.arcsin(x))
print("x = ",np.arccos(x))

print("x = ",np.arctan(x))

x =  [-1, 0, 1]
x =  [-1.57079633  0.          1.57079633]
x =  [3.14159265 1.57079633 0.        ]
x =  [-0.78539816  0.          0.78539816]


### Exponents and logarithms

In [13]:
x = [1,2,3]
print("x=",x)
print("e^x =",np.exp(x))
print("2^x =",np.exp2(x))
print("3^x =",np.power(3,x))

x= [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [14]:
! pip install scipy

     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.8 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.8 kB ? eta -:--:--
     -------------------------------- ----- 51.2/60.8 kB 435.7 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 404.2 kB/s eta 0:00:00
   ---------------------------------------- 0.0/44.5 MB ? eta -:--:--
   ---------------------------------------- 0.1/44.5 MB 2.0 MB/s eta 0:00:23
   ---------------------------------------- 0.2/44.5 MB 2.2 MB/s eta 0:00:20
   ---------------------------------------- 0.3/44.5 MB 2.4 MB/s eta 0:00:19
   ---------------------------------------- 0.5/44.5 MB 2.6 MB/s eta 0:00:17
    --------------------------------------- 0.6/44.5 MB 2.6 MB/s eta 0:00:17
    --------------------------------------- 0.7/44.5 MB 2.4 MB/s eta 0:00:19
    --------------------------------------- 0.8/44.5 MB 2.6 MB/s eta 0:00:18
    ---------

In [15]:
from scipy import special

In [16]:
# Gamma functions (generalized factorials) and related functions
x = [1,5,10]
print("gamma(x)    =",special.gamma(x))
print("ln|gamma(x)|    =",special.gammaln(x))
print("beta(x,2)       =",special.beta(x,2))


gamma(x)    = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)|    = [ 0.          3.17805383 12.80182748]
beta(x,2)       = [0.5        0.03333333 0.00909091]


### Advanced Ufunc Features
##### Specifying the output

In [17]:
y = np.add(x,2)
y

array([ 3,  7, 12])

In [20]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x,10,out=y)
np.add(y,10,out=y)
print(y)

[10. 20. 30. 40. 50.]


In [21]:
y = np.zeros(10)
np.power(2,x,out=y[::2]) # 2^x
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]
